### ISSUE TITLE
Crash when peer call on MONO MO-01K

### ISSUE THREAD

**Issue by jihyeon-kim** [skyway/skyway-android-sdk#10]
device : MONO MO-01K (https://www.nttdocomo.co.jp/product/smart_phone/mo01k/)
sdk ver: 1.0.4

**mediaConnection = peer.call(strPeerId, localStream, option);**

`06-08 22:33:59.933 19451-19580/ D/HelpersAndroid: Attaching thread to JVM@[tid=19580]
06-08 22:33:59.934 19451-19580/ D/HelpersAndroid: Detaching thread from JVM@[tid=19580]
06-08 22:33:59.942 19451-19451/ I/CameraManagerGlobal: Connecting to camera service
06-08 22:34:00.059 19451-19451/ W/ResourceType: No known package when getting name for resource number 0xffffffff
06-08 22:34:00.291 19451-19567/ D/ConnectivityManager: isSuplNetworkCap netCap = [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN]  ret = false
06-08 22:34:00.293 19451-19567/ D/ConnectivityManager: checkLegacyRoutingApiAccess  packageName =  appType = user-app
06-08 22:34:00.293 19451-19567/ W/System.err: java.lang.UnsupportedOperationException: This method is not supported in target SDK version
       at android.net.ConnectivityManager.checkLegacyRoutingApiAccessForDocomo(ConnectivityManager.java:3501)
       at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:2964)
       at org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.requestMobileNetwork(NetworkMonitorAutoDetect.java:349)
       at org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:458)
       at org.webrtc.NetworkMonitor.setAutoDetectConnectivityStateInternal(NetworkMonitor.java:150)
       at org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)
06-08 22:34:00.294 19451-19567/ E/rtc: 
   Fatal error in ../../webrtc/sdk/android/src/jni/androidnetworkmonitor_jni.cc, line 212
   last system error: 0
   Check failed: !jni()->ExceptionCheck()
   Error during CallVoidMethod
   
06-08 22:34:00.294 19451-19567/ A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 19567 (network_thread )`

**Comment by salmoncode** [comment]
We are sorry for the late reply.
Does it occur with the latest version of SkyWay Android SDK (1.1.3)?
If this occurs, please tell us the Android OS version and model number.
